# Generated by Django 5.2 on 2026-04-18 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200, verbose_name='Адресс пункта выдачи')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=20, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('unit', models.CharField(default=[('piece.', 'шт.'), ('piece. (kit)', 'шт. (набор)')], max_length=20)),
                ('prise', models.IntegerField(verbose_name='Цена (руб.)')),
                ('brand', models.CharField(max_length=100, verbose_name='Кондитерская / Бренд')),
                ('type', models.CharField(max_length=100, verbose_name='Тип торта')),
                ('category', models.CharField(max_length=100, verbose_name='Категория торта')),
                ('discount', models.IntegerField(default=0, verbose_name='Действующая скидка (%)')),
                ('stock', models.IntegerField(verbose_name='Кол-во на складе (шт.)')),
                ('descryption', models.TextField(blank=True, verbose_name='Описание товара')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('pickup_code', models.ImageField(upload_to='', verbose_name='Код для получения')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('completed', 'Выполнен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pickuppoint', verbose_name='Адресс пункта выдачи')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
